### ISSUE TITLE
HI. Maybe,we are really destined for each other?

### ISSUE THREAD

**Issue by rougeyan** [shalldie/static#1]
https://www.cnblogs.com/lianmin/p/7691831.html
作者你好 请问这个网站上面的轮播图您是作者吗
因为很久以前有一个QQ群上的网友给我指导我学习前端
发了一份给我跟这个一模一样的插件给我 
包括图片也是一样的
他说是他平常闲下来写的
后来我也毕业事忙,没怎么跟这位网友联系了,
希望这位有缘人是你

**Comment by shalldie** [comment]
😂😂  是我写的。
按照你的说法我就是有缘人 hhh

**Comment by rougeyan** [comment]
> 😂😂 是我写的。
> 按照你的说法我就是有缘人 hhh

hahah.大佬您有联系

**Comment by yanziho** [comment]
> 😂😂 是我写的。
> 按照你的说法我就是有缘人 hhh



> 😂😂 是我写的。
> 按照你的说法我就是有缘人 hhh

haha~ 我可以拥有大佬的联系方式吗

**Comment by shalldie** [comment]
@rougeyan 
不好意思，，我记得之前回了的，刚刚怎么发现竟然没有。
qq 394229785
